# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(205, 120, 150, 150))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap())
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.Image.setStyleSheet('border-style: solid; border-width: 4px; border-color: black;')
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 70, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 70, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setStyleSheet('border-style: solid; border-width: 4px; border-color: black;')
        self.label1.setGeometry(QtCore.QRect(27, 10, 500, 50))
        self.label1.setText("                                          Приложение по распознаванию переломов")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(223, 100, 300, 25))
        self.label2.setText("Слот для изображения")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(185, 265, 293, 25))
        self.label3.setText("Информация о загруженном файле:")
        self.label3.setObjectName("label3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 285, 400, 130))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setStyleSheet('border-style: solid; border-width: 4px; border-color: black;')
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 432, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Распознавание для травматологии"))
        self.pushButton.setText(_translate("MainWindow", "Загрузка"))
        self.pushButton_2.setText(_translate("MainWindow", "Распознавание"))

